squad:
    size: 5
    ammo: 10
    interval: 0
    duration: 0

config:
    verbose: False
    indexed_names: False

orders:
    -
        id: 1
        target: "http://viajeros.com"
        method: POST
        payload: >
            {
                "something": 1
            }

        headers: >
            {
                "X-Its-A-Me": "Mario",
                "X-Purpose": "Testing"
            }

        cookies: >
            {
                "hello": "fuckyou"
            }

    -
        id: 2
        target: "http://httpbin.org/ip"
        method: GET
        payload: >
            {
                "something": 1
            }

        headers: >
            {
                "X-Its-A-Me": "Bombomb"
            }

        cookies: >
            {
                "cookie": "monster"
            }
